Repository gpuctl/gpuctl, pull requests merged in 2024-02, with the labels that each got.

#77 The great refactor: changing the data format
  cmd/satellite/main.go
  internal/database/inmemory.go
  internal/database/inmemory_test.go
  internal/database/interface.go
  internal/database/postgres/postgres.go
  internal/database/unit_tests.go
  internal/gpustats/GPUDataSource.go
  internal/gpustats/_testdata/nvidia/dump_ash01.json
  internal/gpustats/_testdata/nvidia/dump_ash02.json
  internal/gpustats/_testdata/nvidia/dump_ash04.json
  internal/gpustats/_testdata/nvidia/dump_ash05.json
  internal/gpustats/_testdata/nvidia/dump_gpu01.json
  internal/gpustats/_testdata/nvidia/dump_gpu02.json
  internal/gpustats/_testdata/nvidia/dump_gpu03.json
  internal/gpustats/_testdata/nvidia/dump_gpu04.json
  internal/gpustats/_testdata/nvidia/dump_gpu05.json
  internal/gpustats/_testdata/nvidia/dump_gpu10.json
  internal/gpustats/_testdata/nvidia/dump_gpu30.json
  internal/gpustats/_testdata/nvidia/dump_gpu30_altered.json
  internal/gpustats/_testdata/nvidia/dump_gpu36.json
  internal/gpustats/_testdata/nvidia/dump_mira05.json
  internal/gpustats/_testdata/nvidia/dump_mira05.xml
  internal/gpustats/_testdata/nvidia/dump_texel12.json
  internal/gpustats/_testdata/nvidia/texel12.corruptedxml
  internal/gpustats/fake.go
  internal/gpustats/gpustats.go
  internal/gpustats/gpustatus_test.go
  internal/gpustats/nvidia.go
  internal/gpustats/nvidia_test.go
  internal/groundstation/gpustats.go
  internal/uplink/gpustats.go
  internal/webapi/server.go
  internal/webapi/types.go
  internal/webapi/types_testhidden.go
Labels: S-waiting-on-review, C-cleanup, A-satellite, A-groundstation

#81 Prevent satellite from dying instantly
  cmd/satellite/main.go
Labels: C-bug, A-satellite

#84 Add assets package
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  internal/assets/.gitignore
  internal/assets/assets.go
  internal/assets/assets_test.go
Labels: A-CI

#62 Write Dockerfiles for deploying to VM
  .dockerignore
  .gitignore
  Caddyfile
  README.md
  cmd/control/control.go
  cmd/satellite/main.go
  compose.yaml
  control.Dockerfile
  control.toml.default
  frontend.Dockerfile
  frontend/src/App.tsx
  internal/config/client_configuration.go
  internal/config/server_configuration.go
  internal/config/server_configuration_test.go
  satellite.toml.default
Labels: A-CI, S-waiting-on-author, C-feature

#91 Return all new fields from the DB
  internal/database/postgres/postgres.go
  internal/database/unit_tests.go
Labels: S-waiting-on-review, C-bug, A-groundstation

#96 config: Remove `Merge`.
  internal/config/client_configuration.go
  internal/config/client_configuration_test.go
  internal/config/common.go
  internal/config/server_configuration.go
  internal/config/server_configuration_test.go
Labels: S-waiting-on-review, C-cleanup

#99 Deploy on HTTPS
  Caddyfile
  cmd/satellite/main.go
  compose.yaml
  frontend.Dockerfile
  internal/config/client_configuration.go
  internal/config/client_configuration_test.go
  internal/config/common.go
  internal/config/common_test.go
  satellite.toml.default
  secrets/keys.example
Labels: S-waiting-on-author, C-feature

#101 Onboarding over SSH
  .gitignore
  cmd/onboard/main.go
  go.mod
  go.sum
  internal/config/common.go
  internal/config/common_test.go
  internal/onboard/onboard.go
Labels: S-waiting-on-review, C-cleanup

#106 webapi: Add `/api/onboard` route.
  .gitignore
  cmd/control/control.go
  control.toml.default
  internal/config/server_configuration.go
  internal/webapi/authenticators_test.go
  internal/webapi/onboard.go
  internal/webapi/onboard_test.go
  internal/webapi/server.go
  internal/webapi/types.go
  secrets/keys.example
Labels: C-feature, A-api-server

#111 ci: Ensure that `go test -short` works without postgres.
  .github/workflows/ci.yaml
Labels: A-CI, S-waiting-on-review

#110 femto: Change the signature of `Ok`, and always use 200 for it.
  internal/femto/femto.go
  internal/femto/server_test.go
  internal/groundstation/gpustats.go
  internal/groundstation/heartbeat.go
  internal/webapi/alerts.go
  internal/webapi/server.go
Labels: S-waiting-on-review, C-cleanup, A-api-server

#112 ci: Ensure `docker-compose` build works.
  .github/workflows/ci.yaml
  control.Dockerfile
Labels: A-CI, S-waiting-on-review

#114 re-enable `assets` tests.
  internal/assets/assets_test.go
Labels: S-waiting-on-review, C-cleanup

#117 `database`: Deterministic process list merging.
  internal/database/inmemory.go
  internal/database/prune_test.go
Labels: S-waiting-on-review, C-cleanup

#103 Move deployment code to it's own directory
  .github/workflows/ci.yaml
  .gitignore
  README.md
  deploy/.env.example
  deploy/.gitignore
  deploy/Caddyfile
  deploy/README.md
  deploy/compose.yaml
  deploy/control.Dockerfile
  deploy/control.prod.toml
  deploy/frontend.Dockerfile
  deploy/satellite.example.toml
Labels: A-CI, S-waiting-on-review

#133 Update to go 1.22
  .github/workflows/ci.yaml
  deploy/control.Dockerfile
  go.mod
Labels: A-CI, S-waiting-on-review

#141 Cleanup Database Tests
  internal/database/inmemory.go
  internal/database/inmemory_test.go
  internal/database/interface.go
  internal/database/postgres.go
  internal/database/postgres_test.go
  internal/database/unit_test.go
Labels: S-waiting-on-review, C-cleanup

#142 database: Remove `Drop` from database interface.
  internal/database/inmemory.go
  internal/database/interface.go
  internal/database/postgres.go
  internal/database/postgres_test.go
Labels: C-cleanup

#140 Fix front-end auth
  deploy/Caddyfile
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/Components/Navbar.tsx
  frontend/src/Components/SignIn.tsx
  frontend/src/Pages/AdminPanel.tsx
  frontend/src/Pages/MainView.tsx
  frontend/src/Providers/AuthProvider.tsx
  frontend/src/Utils/Utils.tsx
  internal/authentication/authentication.go
  internal/femto/femto.go
  internal/femto/server_test.go
  internal/webapi/authenticators.go
  internal/webapi/authenticators_test.go
  internal/webapi/server.go
  internal/webapi/server_test.go
Labels: A-frontend, A-api-server

#137 passwd: New package to parse `/etc/passwd`
  internal/passwd/passwd.go
  internal/passwd/passwd_test.go
  internal/passwd/testdata/ashtabula
  internal/passwd/testdata/csg_complex
Labels: S-waiting-on-author

#148 Replace uses of workStation with workstation
  frontend/src/App.test.tsx
  frontend/src/Components/DataTable.tsx
  frontend/src/Data.tsx
  frontend/src/Pages/AdminPanel.tsx
  frontend/src/Pages/MainView.tsx
Labels: A-frontend, S-waiting-on-review, C-cleanup

#146 gpustats: Rename `_testdata` to `testdata`.
  internal/gpustats/nvidia_test.go
  internal/gpustats/testdata/nvidia/ash03.faultycall
  internal/gpustats/testdata/nvidia/dump_ash01.json
  internal/gpustats/testdata/nvidia/dump_ash01.xml
  internal/gpustats/testdata/nvidia/dump_ash02.json
  internal/gpustats/testdata/nvidia/dump_ash02.xml
  internal/gpustats/testdata/nvidia/dump_ash04.json
  internal/gpustats/testdata/nvidia/dump_ash04.xml
  internal/gpustats/testdata/nvidia/dump_ash05.json
  internal/gpustats/testdata/nvidia/dump_ash05.xml
  internal/gpustats/testdata/nvidia/dump_gpu01.json
  internal/gpustats/testdata/nvidia/dump_gpu01.xml
  internal/gpustats/testdata/nvidia/dump_gpu02.json
  internal/gpustats/testdata/nvidia/dump_gpu02.xml
  internal/gpustats/testdata/nvidia/dump_gpu03.json
  internal/gpustats/testdata/nvidia/dump_gpu03.xml
  internal/gpustats/testdata/nvidia/dump_gpu04.json
  internal/gpustats/testdata/nvidia/dump_gpu04.xml
  internal/gpustats/testdata/nvidia/dump_gpu05.json
  internal/gpustats/testdata/nvidia/dump_gpu05.xml
  internal/gpustats/testdata/nvidia/dump_gpu10.json
  internal/gpustats/testdata/nvidia/dump_gpu10.xml
  internal/gpustats/testdata/nvidia/dump_gpu30.json
  internal/gpustats/testdata/nvidia/dump_gpu30.xml
  internal/gpustats/testdata/nvidia/dump_gpu30_altered.json
  internal/gpustats/testdata/nvidia/dump_gpu30_altered.xml
  internal/gpustats/testdata/nvidia/dump_gpu36.json
  internal/gpustats/testdata/nvidia/dump_gpu36.xml
  internal/gpustats/testdata/nvidia/dump_mira05.json
  internal/gpustats/testdata/nvidia/dump_mira05.xml
  internal/gpustats/testdata/nvidia/gatherdata.sh
  internal/gpustats/testdata/nvidia/gpu05.corruptedxml
  internal/gpustats/testdata/nvidia/texel12.corruptedxml
Labels: S-waiting-on-review, C-cleanup

#144 femto: Don't pass `http.ResponseWriter` by pointer.
  internal/femto/femto.go
Labels: S-waiting-on-review, C-cleanup

#152 Adds new endpoint for duration delta from now since last seen
  internal/broadcast/types.go
  internal/webapi/server.go
Labels: S-waiting-on-author, C-feature, A-api-server

#150 DRAFT: Automatic SSH Restart
  cmd/control/control.go
  go.mod
  go.sum
  internal/config/server_configuration.go
  internal/groundstation/autocontact.go
  internal/groundstation/autocontact_test.go
  internal/onboard/onboard.go
Labels: S-waiting-on-author, C-feature

#118 config: Remove references to client & server.
  cmd/control/control.go
  cmd/satellite/main.go
  internal/config/groundstation.go
  internal/config/groundstation_test.go
  internal/config/satellite.go
  internal/config/satellite_test.go
Labels: S-waiting-on-review, C-cleanup

#160 Run `go mod tidy`
  go.mod
  go.sum
Labels: S-waiting-on-review, C-cleanup

#159 Consolidate ssh code into `onboard`.
  cmd/control/control.go
  cmd/onboard/main.go
  internal/groundstation/autocontact.go
  internal/groundstation/autocontact_test.go
  internal/onboard/onboard.go
  internal/onboard/restart_test.go
  internal/webapi/onboard.go
  internal/webapi/onboard_test.go
  internal/webapi/server.go
  internal/webapi/server_test.go
Labels: S-waiting-on-review, C-cleanup

#166 Send user information satellite -> groundstation.
  cmd/satellite/main.go
  internal/gpustats/nvidia.go
  internal/gpustats/nvidia_test.go
  internal/procinfo/pidtouser.go
  internal/procinfo/pidtouser_test.go
  internal/procinfo/testdata/ashtabula
  internal/uplink/gpustats.go
Labels: S-waiting-on-author, C-feature, A-groundstation

#143 Return groups from the database
  internal/broadcast/types.go
  internal/broadcast/types_test.go
  internal/database/inmemory.go
  internal/database/interface.go
  internal/database/postgres.go
  internal/database/unit_test.go
  internal/groundstation/autocontact_test.go
  internal/uplink/heartbeat.go
  internal/webapi/server.go
  internal/webapi/server_test.go
Labels: S-waiting-on-review, C-feature, C-cleanup, A-api-server

#178 procinfo: Use `golang.org/x/sys/` instead of `syscall`
  go.mod
  internal/procinfo/pidtouser.go
Labels: S-waiting-on-review, C-cleanup

#164 Implement "last seen" warnings on the front-end
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/Components/WorkstationCardMinimal.tsx
  frontend/src/Data.tsx
  frontend/src/Pages/MainView.tsx
  frontend/src/Utils/Utils.tsx
Labels: S-waiting-on-review

#184 webapi file upload endpoint
  internal/broadcast/types.go
  internal/database/inmemory.go
  internal/database/interface.go
  internal/database/postgres.go
  internal/database/testdata/more.txt
  internal/database/testdata/uploadtest.pdf
  internal/database/unit_test.go
  internal/femto/femto.go
  internal/groundstation/autocontact_test.go
  internal/webapi/server.go
  internal/webapi/server_test.go
  internal/webapi/testdata/more.txt
  internal/webapi/testdata/uploadtest.pdf
Labels: S-waiting-on-author, C-feature, A-api-server

#193 Deployment fixes
  deploy/Caddyfile
  deploy/compose.yaml
  deploy/control.prod.toml
Labels: S-waiting-on-review, C-bug

#202 `RemoveMachine` postgres implementation fixes
  internal/database/postgres.go
  internal/database/unit_test.go
  internal/webapi/server.go
Labels: S-waiting-on-review, C-bug, A-groundstation

#230 Improve logging of errors in production
  cmd/control/control.go
  internal/database/prune.go
Labels: S-waiting-on-review, C-bug, C-cleanup

#232 Track machine owner in the database.
  internal/broadcast/types.go
  internal/database/inmemory.go
  internal/database/postgres.go
  internal/database/unit_test.go
Labels: S-waiting-on-review, C-feature
